import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '../app/component/Navbar/Navbar';
// import {state,account,connectWallet} from './utils/apifeature';
import { state,account,connectWallet } from './utils/apifeature';
import { Providers } from './features/provider';
// import { Providers } from "../app/features/provider";
import ContractConnector from './utils/apifeature';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
          {/* <Navbar state={state} account={account} connectWallet={connectWallet}/> */}
      <body className={inter.className}>
       <Providers>
         <ContractConnector/>
        {children}
       </Providers>     
        </body>
    </html>
  )
}
